#!/bin/bash
# release version
version=3.1.6

usage(){
    echo $"Usage: $0 [host] [password] (default host is 127.0.0.1 and default password is '1234')"
}
dbHost=${2}
dbHost=${dbHost:=127.0.0.1}
dbPassword=${3}
dbPassword=${dbPassword:=1234}

initdb()
{
	init_onedb ams
	#init_onedb ams_${version}
	init_onedb hbs
	init_onedb job
	init_onedb mon
	init_onedb rdb
	
}
init_onedb(){
	echo init db n9e_${1}
	mysql -uroot -p${dbPassword} -h ${dbHost} < sql/n9e_${1}.sql
}

case "$1" in
    -h)
		usage
		;;
	*)
		initdb
esac